---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: es-http-tls
  namespace: es
spec:
  isCA: true
  duration: 2160h # 90d 2160h
  renewBefore: 168h # 7d 168h
  dnsNames:
    - es-client
    - es-client.es.svc
    - es-client.es.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: es-http-tls
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kibana-tls
  namespace: es
spec:
  isCA: true
  duration: 2h # 90d
  renewBefore: 1h # 7d
  dnsNames:
    - localhost
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: kibana-tls