---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: es
  name: kibana-config
  labels:
    app: kibana
data:
  kibana.yml: |-
    server.host: 0.0.0.0
    server.ssl.enabled: true
    server.ssl.certificate: /usr/share/kibana/config/certs/kibana/tls.crt
    server.ssl.key: /usr/share/kibana/config/certs/kibana/tls.key
    elasticsearch: 
      hosts: ${ELASTICSEARCH_HOSTS}
      username: ${ELASTICSEARCH_USER}
      password: ${ELASTICSEARCH_PASSWORD}
      ssl:
        key: /usr/share/kibana/config/certs/es/tls.key
        certificate: /usr/share/kibana/config/certs/es/tls.crt
        certificateAuthorities: /usr/share/kibana/config/certs/es/ca.crt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: es
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.6.1
        ports:
        - containerPort: 5601
          name: kibana-svc
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "https://es-client.es.svc.cluster.local:9200"
        - name: ELASTICSEARCH_USER
          value: "elastic"
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: es-pw-elastic
              key: password
        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/config/kibana.yml
          readOnly: true
          subPath: kibana.yml
        - name: es-http-tls
          mountPath: /usr/share/kibana/config/certs/es
          readOnly: true
        - name: kibana-certs
          mountPath: /usr/share/kibana/config/certs/kibana
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: kibana-config
      - name: es-http-tls
        secret:
          secretName: es-http-tls
      - name: kibana-certs
        secret:
          secretName: kibana-tls
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-svc
  namespace: es
  labels:
    service: kibana-svc
spec:
  type: NodePort
  ports:
  - port: 5601
    name: kibana-svc
  selector:
    app: kibana